### Numpy

Alinear algebraic python library that works woth array created by Travis Oliphant and stands for Numerical Python

Numpy is a core library for scientific and engineering computation

Numpy are faster than list due to the loclity of reference in computer science.

All element in a numpy array are homogeneous while a list can have heteregeous elements


----
##### Array
An array is a grid of values and contains raw data.

In [1]:
#### import numpy
import numpy as np

In [459]:
num = [1,2,3,4,5,6,7,8,9,0]

In [460]:
print(num)
print(type(num))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
<class 'list'>


### creating an array
__np.array()__ creates a numpy array from a list or tuple,

In [461]:
# creating an array
num_array = np.array(num)

In [462]:
print(num_array)
print(type(num_array))

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>


In [3]:
# an array object in numpy is called ndarray
# we pass a list,tuple,any array-object to array()
arr = np.array((2,4,6,8,0))
print(arr)

[2 4 6 8 0]


In [526]:
print(type(arr))

<class 'numpy.ndarray'>


#### np.arange(start,stop,step)

np.arange => create a sequnce of of number based on the given parameter

    start = the staarting number of the sequence
    stop = optional, the ending number of a sequence
    step = consecutive spacing or step s for the sequence

In [541]:
np.arange(15,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [540]:
score = np.arange(1,15)
print(score)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [542]:
odd_score = np.arange(1,15,2)
print(odd_score)

[ 1  3  5  7  9 11 13]


#### creating an array filled with zeros, ones,eye

__np.zeros()__

Often use to initialize an array before filling them with data

In [563]:
# np.zeroes
zero_one_dim = np.zeros(5)
print(zero_one_dim)

[0. 0. 0. 0. 0.]


In [579]:
zero_two_dim = np.zeros((5,2))
print(zero_two_dim)
print('dimension:',zero_one_dim)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
dimension: [0. 0. 0. 0. 0.]


In [561]:
zero_two_dim = np.zeros((2,5))
print(zero_two_dim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### ones

To create arrays for comparison and scale other arrays

In [577]:
ones_two_dim = np.ones((5,2))
print(ones_two_dim)
print('dimension:',ones_two_dim.ndim)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
dimension 2


In [578]:
ones_three_dim = np.ones((5,2,10))
print(ones_three_dim)
print('dimension:',ones_three_dim.ndim)

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]
dimension: 3


#### np.eye()

np.eye(x) take in one argument wich most be a positive integer

np.eye() creates a 2-D array

An Identity matrix is a square matrix with ones on the diagomal and zeros on the others

In [602]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

#### np.linspace()

`np.linspace(start,stop,num=50)`
start and stop are a must while num is optional

by defualt, num is 50

This creates arrays with equally space numbers.

Useful for scientific computing, data analysis and plotting

In [616]:
axis = np.linspace(0,5)
print(axis)
print('\n\nlength: ', len(axis))

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


length:  50


In [617]:
# i want 10 numbers only
axis = np.linspace(0,5,10)
print(axis)
print('\n\nlength: ', len(axis))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


length:  10


In [620]:
axis = np.linspace(0,10,5)
print(axis)
print('length: ', len(axis))
# you would observe that they are all evnenly soaced numbers

[ 0.   2.5  5.   7.5 10. ]
length:  5


#### np.random.rand()

Creates an array of floating point numbers drawn from a uniform distribution over the interval 0 and 1.

By default it takes in no argument and returns a single floating number (0-D array)

it takes in the shape of the array you want

Used in Monte Carlo simulations, statistical analysis, and random sampling.

In [662]:
zero = np.random.rand() # 0-D array
print(zero)

0.2807585373953796


In [659]:
one = np.random.rand(5) # 1-D array
print(one)
print('Dimension: ', one.ndim)

[0.2536712  0.86007743 0.30823084 0.5534162  0.19185015]
Dimension:  1


In [664]:
two = np.random.rand(5,4) # 2-D array
print(two)
print('Dimension: ', two.ndim)

[[0.69737022 0.30348864 0.57584878 0.87471783]
 [0.02091873 0.72404924 0.51375653 0.59510469]
 [0.80775573 0.06016164 0.98287409 0.6040349 ]
 [0.6544328  0.54990208 0.09334567 0.33576806]
 [0.64201673 0.90562303 0.57412514 0.56672039]]
Dimension:  2


In [665]:
three = np.random.rand(2,3,4) # 3-D array
print(three)
print('Dimension: ', three.ndim)

[[[0.6343534  0.18452056 0.44378254 0.13221345]
  [0.72990394 0.44480323 0.89534655 0.49876738]
  [0.50791851 0.75296167 0.88309405 0.19032165]]

 [[0.40601819 0.70751679 0.63670414 0.08929978]
  [0.61936264 0.26875279 0.14378367 0.03734884]
  [0.15114883 0.87356464 0.01083651 0.90723963]]]
Dimension:  3


In [666]:
four = np.random.rand(2,3,4,2) # 4-D array
print(four)
print('Dimension: ', four.ndim)

[[[[0.28114306 0.76529621]
   [0.75973863 0.62422806]
   [0.73620699 0.12906164]
   [0.15633801 0.51858941]]

  [[0.35415601 0.7326499 ]
   [0.99769359 0.64982791]
   [0.72168887 0.79684538]
   [0.08218649 0.59830091]]

  [[0.96185751 0.7593719 ]
   [0.52419873 0.50457659]
   [0.54296936 0.7291153 ]
   [0.89491404 0.14526391]]]


 [[[0.28456093 0.20101451]
   [0.18184379 0.86630754]
   [0.53367324 0.25011042]
   [0.01615413 0.00234943]]

  [[0.82410981 0.0323201 ]
   [0.08050329 0.90839981]
   [0.63798531 0.8594926 ]
   [0.83411743 0.94762505]]

  [[0.93426346 0.52169852]
   [0.58124223 0.16131529]
   [0.50748551 0.3143802 ]
   [0.90510485 0.77745625]]]]
Dimension:  4


#### np.random.randn()

creates an array of random flaoting point numbers drawn from a standard normal distribution which has a mean of 0 and variance of 1

Commonly used in Monte Carlo simulation, statiscal analysis and machine learning

In [668]:
zero = np.random.randn()
print(zero)

2.6357984447158267


In [671]:
two = np.random.randn(3,5)
print(two)

[[ 0.86417173  1.27932437  1.12034666 -0.89422205  1.59274491]
 [ 0.38406452  0.05430758 -0.37691042 -0.35080116  0.63079379]
 [ 1.75701735  1.4169813   0.61292102 -0.22773805 -0.57882516]]


In [674]:
three = np.random.randn(2,5,3)
print(three)

[[[-0.27197457  0.42153723  0.17345015]
  [-0.07116236  1.63905782  0.34716461]
  [-0.32486266  1.1559995  -0.97688637]
  [-0.52679471  0.53227098  0.91939182]
  [-2.11369122 -0.55017872  1.49181596]]

 [[-0.02555401 -0.39278805 -0.61236147]
  [ 0.90184911 -0.38958181 -0.84304676]
  [-0.748892   -0.02989024 -2.24924849]
  [-1.2002714   1.24457297 -0.5992258 ]
  [-0.93548405  1.24765419 -0.36872286]]]


#### np.random.randint()

Creates an array of discrete numbers from a givren range parameter.

`np.random(low=0,high,size=option)`

commonly used in  Monte Carlo simulations, data randomization, and cryptographic applications

In [726]:
age = np.random.randint(10)
print(age)

7


In [730]:
ages = np.random.randint(0,10)
print(ages)

3


In [739]:
# need an array of 5 ages
ages = np.random.randint(0,10,5)
print(ages)

[2 1 0 9 8]


#### dimensions in Arrays
- these are nested arrays

- 0-D Arrays

Zero dimension array or scalar

In [5]:
arr = np.array(34)
print(arr)

34


In [6]:
age = np.array(25)
print(age)

25


- 1-D Arrays

One dimension arrays or uni-dimensional

In [7]:
ages = np.array([25,23,27,29,30])
print(ages)

[25 23 27 29 30]


In [8]:
heights = np.array((123,122,100,123,98))
print(heights)

[123 122 100 123  98]


- 2-D arrays

Often used to represent __matrix__ or 2nd order tensors

In [9]:
health = np.array([[23,34,25,31],[123,200,192,128]])
print(health)

[[ 23  34  25  31]
 [123 200 192 128]]


- 3 D array

3rd order tensor, an array having 2-D arrays as its element

In [10]:
health_score = np.array([[[23,34,25,31],[123,200,192,128]],[[50,60,70,80],[99,88,77,66]]])
print(health_score)

[[[ 23  34  25  31]
  [123 200 192 128]]

 [[ 50  60  70  80]
  [ 99  88  77  66]]]


In [11]:
#### checking the dimensions
# ndim

In [12]:
print(health.ndim)

2


In [13]:
print(age.ndim)

0


In [14]:
print(health_score.ndim)

3


In [15]:
# There are no limit to number of dimensions
taste = np.array([11,22,33,44,55], ndmin=6)

In [16]:
print(taste)

[[[[[[11 22 33 44 55]]]]]]


In [17]:
print(taste.ndim)

6


#### Accesing array by indexing

In [37]:
# accessing a 1-D array
meal_list = np.array(["Apples", "Bananas", "Oranges", "Grapes", "Berries", "Melons", "Carrots", "Potatoes", "Lettuce", "Tomatoes", "Cucumbers", "Broccoli", "Bread", "Pasta", "Rice", "Cereal", "Milk", "Cheese", "Yogurt", "Butter", "Beef", "Chicken", "Pork", "Fish", "Eggs", "Nuts", "Seeds", "Sweets", "Drinks"])
print(meal_list)

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']


In [38]:
print(meal_list.ndim)

1


In [31]:
# accesing the second item in meal_list
second_meal = meal_list[1]
print(second_meal)

Bananas


In [32]:
# accesing the last item in meal_list
last_meal = meal_list[-1]
print(last_meal)

Drinks


In [33]:
# accesing the 17th item in meal_list
seven_meal = meal_list[6]
print(seven_meal)

Carrots


In [35]:
# accessing a 2-D array

store_products = np.array(
    [
        ['product 1', 'product 2', 'product 3', 'product 4', 'product 5', 'product 6', 'product 7', 'product 8', 'product 9', 'product 10', 'product 11', 'product 12', 'product 13', 'product 14', 'product 15', 'product 16', 'product 17', 'product 18', 'product 19', 'product 20', 'product 21', 'product 22', 'product 23', 'product 24', 'product 25', 'product 26', 'product 27', 'product 28', 'product 29'],
        ["Apples", "Bananas", "Oranges", "Grapes", "Berries", "Melons", "Carrots", "Potatoes", "Lettuce", "Tomatoes", "Cucumbers", "Broccoli", "Bread", "Pasta", "Rice", "Cereal", "Milk", "Cheese", "Yogurt", "Butter", "Beef", "Chicken", "Pork", "Fish", "Eggs", "Nuts", "Seeds", "Sweets", "Drinks"]
    ]
)

print(store_products)

[['product 1' 'product 2' 'product 3' 'product 4' 'product 5' 'product 6'
  'product 7' 'product 8' 'product 9' 'product 10' 'product 11'
  'product 12' 'product 13' 'product 14' 'product 15' 'product 16'
  'product 17' 'product 18' 'product 19' 'product 20' 'product 21'
  'product 22' 'product 23' 'product 24' 'product 25' 'product 26'
  'product 27' 'product 28' 'product 29']
 ['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
  'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
  'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken'
  'Pork' 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']]


In [39]:
print(store_products.ndim)

2


In [41]:
# accesing the first item in store_product
print(store_products[0])

['product 1' 'product 2' 'product 3' 'product 4' 'product 5' 'product 6'
 'product 7' 'product 8' 'product 9' 'product 10' 'product 11'
 'product 12' 'product 13' 'product 14' 'product 15' 'product 16'
 'product 17' 'product 18' 'product 19' 'product 20' 'product 21'
 'product 22' 'product 23' 'product 24' 'product 25' 'product 26'
 'product 27' 'product 28' 'product 29']


In [43]:
# what about the first item in the first item
print(store_products[0][0])
# the pattern of accessing items is preferably used in List but not ideally in numpy array

product 1


In [44]:
# accessing the product 1 using numpy 
print(store_products[0,0])

product 1


In [67]:
# creating a 7-D array

seventh_dim = np.array(np.random.randint(10,100,10), ndmin=7)

In [68]:
print(seventh_dim)

[[[[[[[33 17 88 73 12 26 30 87 32 69]]]]]]]


In [69]:
# accesing the last item using list
last_item = seventh_dim[0][0][0][0][0][0][-1]
print(last_item)

69


In [70]:
# using numpy
last_item = seventh_dim[0,0,0,0,0,0,-1]
print(last_item)

69


#### Slicing

`arr[start:end:step,index]`

Slicing a 1-D array

In [71]:
print(meal_list)

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']


In [73]:
len(meal_list) # length of meal_list

29

In [75]:
# slice from begiinning to ending
meal_1 = meal_list[:]
print(meal_1)
# by default, start = 0, end = ending

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks'] 29


In [78]:
print(meal_list[0:])

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']


In [80]:
print(meal_list[:-1])
# last item was sliced out

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets']


In [85]:
print(meal_list[::2])
# be default step = 1, this returns the item after every two step

['Apples' 'Oranges' 'Berries' 'Carrots' 'Lettuce' 'Cucumbers' 'Bread'
 'Rice' 'Milk' 'Yogurt' 'Beef' 'Pork' 'Eggs' 'Seeds' 'Drinks']


Slicing a 2-D array

In [86]:
print(store_products)

[['product 1' 'product 2' 'product 3' 'product 4' 'product 5' 'product 6'
  'product 7' 'product 8' 'product 9' 'product 10' 'product 11'
  'product 12' 'product 13' 'product 14' 'product 15' 'product 16'
  'product 17' 'product 18' 'product 19' 'product 20' 'product 21'
  'product 22' 'product 23' 'product 24' 'product 25' 'product 26'
  'product 27' 'product 28' 'product 29']
 ['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
  'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
  'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken'
  'Pork' 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']]


In [91]:
# slicing the fisrt 5 item in the first list in the above 2-D array
print(store_products[0,:5])

['product 1' 'product 2' 'product 3' 'product 4' 'product 5']


In [90]:
# slicing the fisrt 5 item in the second list in the above 2-D array
print(store_products[1,:5])

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries']


In [93]:
# returning the second item in both list in the array
print(store_products[:,1])

['product 2' 'Bananas']


In [96]:
# returning the second item in both list in the array
print(store_products[0:,1])

['product 2' 'Bananas']


In [98]:
print(store_products[:,:])

[['product 1' 'product 2' 'product 3' 'product 4' 'product 5' 'product 6'
  'product 7' 'product 8' 'product 9' 'product 10' 'product 11'
  'product 12' 'product 13' 'product 14' 'product 15' 'product 16'
  'product 17' 'product 18' 'product 19' 'product 20' 'product 21'
  'product 22' 'product 23' 'product 24' 'product 25' 'product 26'
  'product 27' 'product 28' 'product 29']
 ['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
  'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
  'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken'
  'Pork' 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']]


data types in NumPy:

| Data Type | Description |
|---|---|
| `int8`, `int16`, `int32`, `int64` | Signed integers with different bit sizes (8, 16, 32, and 64 bits, respectively). signed int are both positive or negative |
| `uint8`, `uint16`, `uint32`, `uint64` | Unsigned integers with different bit sizes (8, 16, 32, and 64 bits, respectively). unsigned int are positive |
| `float16`, `float32`, `float64` | Floating-point numbers with different precision levels (half, single, and double precision, respectively). |
| `complex64`, `complex128` | Complex numbers with different precision levels (64 and 128 bits, respectively). |
| `bytes_` | Represents fixed-size sequences of 8-bit bytes. |
| `str_` | Represents fixed-size sequences of Unicode characters. |
| `unicode_` | Represents fixed-size sequences of Unicode characters (deprecated). |
| `datetime64` | Represents dates and times with different resolutions (nanoseconds, microseconds, milliseconds, seconds, minutes, hours, days, etc.). |
| `timedelta64` | Represents time intervals with different resolutions (nanoseconds, microseconds, milliseconds, seconds, minutes, hours, days, etc.). |


In [478]:
# Creating arrays of different data types
int_array = np.array([1, 2, 3, -4, 5])  # signed integer  array
unsigned_int = np.array([1,2,3,4,5], dtype='uint') # unsigned int
float_array = np.array([1.0, 2.0, 3.0, 4.0, 5.0])  # Floating-point array
complex_array = np.array([1+2j, 3+4j, 5+6j])  # Complex number array
bool_array = np.array([True, False, True, False, True])  # Boolean array
string_array = np.array(["apple", "banana", "orange", "grape", "cherry"])  # String array
date_array = np.array(['2002-01-01', '2003-02-21'], dtype='datetime64')

# Printing the data types of each array
print("Integer array data type:\t", int_array.dtype)
print("Unsigneed Integer array data type:\t", unsigned_int.dtype)
print("Floating-point array data type:\t", float_array.dtype)
print("Complex number array data type:\t", complex_array.dtype)
print("Boolean array data type:\t", bool_array.dtype)
print("String array data type:\t", string_array.dtype)
print("Datetime array data type:\t", date_array.dtype)

Integer array data type:	 int64
Unsigneed Integer array data type:	 uint64
Floating-point array data type:	 float64
Complex number array data type:	 complex128
Boolean array data type:	 bool
String array data type:	 <U6
Datetime array data type:	 datetime64[D]


In [100]:
print(meal_list)

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']


In [102]:
print(meal_list.dtype)

<U9


In [107]:
print(heights)

[123 122 100 123  98]


In [109]:
print(heights.dtype)

int64


In [139]:
date = np.array(['2002-01-01', '2003-02-21'])

In [140]:
print(date.dtype)

<U10


#### creating defined data type

`dtype='V'`

In [143]:
# defining the array as a Datetime data type

date = np.array(['2002-01-01', '2003-02-21'], dtype='M')

In [144]:
print(date.dtype)

datetime64[D]


#### we can define the size(byte) of some data type

`i,u,f,S,U`

`dtype='S10'`

In [147]:
fruit = np.array(['Carrots', 'Potatoes', 'Lettuce', 'Tomatoes'], dtype='S10')

In [148]:
print(fruit)

[b'Carrots' b'Potatoes' b'Lettuce' b'Tomatoes']


#### integer and their bit size range


    Data Type	Range
    int8	-128 to 127
    in16	-32768 to 32767
    in32	-2147483648 to 2147483647
    in64	-9223372036854775808 to 9223372036854775807

In [471]:
dice = np.array([1,2,3,4,5,6,7,8,9,0], dtype='int8') #integer of 2bit
# -2**31 to 2**31**(-1)

In [472]:
print(dice)
print(dice.dtype)

[1 2 3 4 5 6 7 8 9 0]
int8


In [479]:
charr = np.array(['a', 2, 3], dtype='int32')
# this returns an error when we try converting the datatype to 'i' (integer) due to the presence of 'STRING'

ValueError: invalid literal for int() with base 10: 'a'

In [488]:
# we can convert integer to string but not the other way
charr = np.array(['a', 2, 3], dtype='str')
print(charr)
print(charr.dtype)

['a' '2' '3']
<U1


In [487]:
color = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'purple', 'maroon']
color = np.array(color, dtype='str')
print(color)
print(color.dtype)

['red' 'orange' 'yellow' 'green' 'blue' 'indigo' 'purple' 'maroon']
<U6


#### astype()

- best way to change the data type of an existing array

- Always ake a copy 

```
arr = np.array([1,2,3,4,5])
newarr = arr.astype('f')
```

In [191]:
score = np.array([60,45,98,100,-56, 0])
print(score)
print(score.dtype)

[ 60  45  98 100 -56   0]
int64


In [489]:
# changing the data type to float
new_score = score.astype('float')
print(new_score)
print(new_score.dtype)

[ 60.  45.  98. 100. -56.   0.]
float64


In [193]:
# try converting data type to boolean
bool_score = score.astype(bool)
print(bool_score)
print(bool_score.dtype)
# all numbers are TRUE but 0

[ True  True  True  True  True False]
bool


#### copy vs view

Copy creates a new array and any data manipulation doesn't affect the original array

View returns the original array and any manipulation affects the original array

In [214]:
# copy
phone_brands = [
    "Samsung",
    "Apple",
    "Huawei",
    "Sony",
    "Nokia",
    "Google",
    "OnePlus",
    "HTC",
    "ASUS"
]
phone_brands = np.array(phone_brands)

In [215]:
new_phones = phone_brands.copy()
print(new_phones)

['Samsung' 'Apple' 'Huawei' 'Sony' 'Nokia' 'Google' 'OnePlus' 'HTC' 'ASUS']


In [216]:
# lets replace 'HTC' to 'Vivo'
new_phones[7] = 'Vivo'
print(phone_brands)
print(new_phones)
# the orignal array is not affected

['Samsung' 'Apple' 'Huawei' 'Sony' 'Nokia' 'Google' 'OnePlus' 'HTC' 'ASUS']
['Samsung' 'Apple' 'Huawei' 'Sony' 'Nokia' 'Google' 'OnePlus' 'Vivo'
 'ASUS']


In [223]:
# view
colors = [
    "red",  
    "orange", 
    "yellow", 
    "green", 
    "blue", 
    "indigo",  
    "purple", 
    "pink"
]
colors = np.array(colors)

In [224]:
new_colors = colors.view()
print(new_colors)

['red' 'orange' 'yellow' 'green' 'blue' 'indigo' 'purple' 'pink']


In [226]:
# lets replace 'pink' to maroon
new_colors[-1] = 'maroon'
print(colors)
print(new_colors)
# both the new array and the original array has been affected

['red' 'orange' 'yellow' 'green' 'blue' 'indigo' 'purple' 'maroon']
['red' 'orange' 'yellow' 'green' 'blue' 'indigo' 'purple' 'maroon']


__How do we know if an array owns its data?__

copies owns their data, as any data manipulation to it does not affect the orignal data

view does not own its data and any manipulation affects the orignal array

calling the `base` attribute on an array returns __None__ if the array owns its data, else it returns the array

In [436]:
print(new_phones.base) # copy
print(new_colors.base) # view

None
['red' 'orange' 'yellow' 'green' 'blue' 'indigo' 'purple' 'maroon']


#### Shape
This returns a tuple showing the size of the array along size its dimension


In [298]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print('shape',arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
shape (2, 4)


In [297]:
arr = np.array([[1,2,3],[5,6,7],[6,7,8],[9,1,2]])
print(arr)
print('shape', arr.shape)

[[1 2 3]
 [5 6 7]
 [6 7 8]
 [9 1 2]]
shape (4, 3)


In [300]:
arr = np.array(np.random.normal(10,20,5), ndmin=1)
print(arr)
print('shape', arr.shape)

[-3.48455058 29.75033767 56.30315122 15.27172273 24.6762351 ]
shape (5,)


In [303]:
arr = np.array(np.random.normal(10,20,5), ndmin=3)
print(arr)
print('shape', arr.shape)

[[[33.97490283 19.8717124  -0.12290764 -3.49690681 -6.31337058]]]
shape (1, 1, 5)


In [309]:
arr = np.array([np.random.normal(10,20,2) for i in range(5)], ndmin=2)
print(arr)
print('shape', arr.shape)

[[38.95324785  7.12600445]
 [48.57049425 29.78563091]
 [36.35906005 19.15735896]
 [-6.26322141  9.37084197]
 [11.17694376 48.99984103]]
shape (5, 2)


In [325]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


#### Reshape

This is the changing of the shape of an array

`reshape(row,columns,subarrays)`

__reshape array is a view as any data manipulation affects the original__

In [414]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [415]:
print(arr)
print(arr.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [416]:
# reshape
newarr = arr.reshape(5,2)

In [417]:
print(newarr)
print('array shape', newarr.shape)
print('array dimension', newarr.ndim)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array shape (5, 2)
array dimension 2


In [418]:
# note that you can only reshape it to fit
newarr = arr.reshape(3,2)
# this returns an error

ValueError: cannot reshape array of size 10 into shape (3,2)

In [419]:
newarr = arr.reshape(2,5) # 2-D array

In [420]:
print(newarr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [421]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [422]:
newarr = arr.reshape(2, 3, 2) # 3-D array
# [ [  [][][]  ]    [  [][][]   ]   ]

In [423]:
print(newarr)
print('array shape', newarr.shape)
print('array dimension', newarr.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
array shape (2, 3, 2)
array dimension 3


In [424]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [425]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [426]:
newarr = arr.reshape(3,4,2) # 3-D array

In [427]:
print(newarr)
print('array shape', newarr.shape)
print('array dimension', newarr.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
array shape (3, 4, 2)
array dimension 3


In [428]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191])

In [429]:
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191]


In [430]:
newarr = arr.reshape(8,2,3,4) # 4-D array

In [431]:
print(newarr)

[[[[  0   1   2   3]
   [  4   5   6   7]
   [  8   9  10  11]]

  [[ 12  13  14  15]
   [ 16  17  18  19]
   [ 20  21  22  23]]]


 [[[ 24  25  26  27]
   [ 28  29  30  31]
   [ 32  33  34  35]]

  [[ 36  37  38  39]
   [ 40  41  42  43]
   [ 44  45  46  47]]]


 [[[ 48  49  50  51]
   [ 52  53  54  55]
   [ 56  57  58  59]]

  [[ 60  61  62  63]
   [ 64  65  66  67]
   [ 68  69  70  71]]]


 [[[ 72  73  74  75]
   [ 76  77  78  79]
   [ 80  81  82  83]]

  [[ 84  85  86  87]
   [ 88  89  90  91]
   [ 92  93  94  95]]]


 [[[ 96  97  98  99]
   [100 101 102 103]
   [104 105 106 107]]

  [[108 109 110 111]
   [112 113 114 115]
   [116 117 118 119]]]


 [[[120 121 122 123]
   [124 125 126 127]
   [128 129 130 131]]

  [[132 133 134 135]
   [136 137 138 139]
   [140 141 142 143]]]


 [[[144 145 146 147]
   [148 149 150 151]
   [152 153 154 155]]

  [[156 157 158 159]
   [160 161 162 163]
   [164 165 166 167]]]


 [[[168 169 170 171]
   [172 173 174 175]
   [176 177 178 179]]

  [[180 181

In [432]:
print('array shape', newarr.shape)
print('array dimension', newarr.ndim)

array shape (8, 2, 3, 4)
array dimension 4


In [444]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191])

In [445]:
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191]


In [448]:
# subarray = -1, reshape the array to its best possible form
newarr = arr.reshape(8,2,3,-1)

In [449]:
print('array shape', newarr.shape)
print('array dimension', newarr.ndim)

array shape (8, 2, 3, 4)
array dimension 4


#### Iteration Arrays

`nditer()` iterates over all the data in the array and returns each

In [514]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])
newarr = arr.reshape(3,4,-1).copy()

In [517]:
newarr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [518]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [458]:
for i in np.nditer(newarr):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [ ]:
array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

#### Basic mathematical operation 

In [494]:
pre_sale = np.array([1,2,3,4,5])
cur_sale = np.array([9,8,7,6,5])

In [503]:
# addition
print(pre_sale + cur_sale)

[10 10 10 10 10]


In [504]:
# multiplication
print(pre_sale * cur_sale)

[ 9 16 21 24 25]


In [505]:
# subtraction
print(pre_sale - cur_sale)

[-8 -6 -4 -2  0]


In [506]:
# division
print(pre_sale / cur_sale)

[0.11111111 0.25       0.42857143 0.66666667 1.        ]


In [507]:
# floor division
print(pre_sale // cur_sale)

[0 0 0 0 1]


In [508]:
# modulus
print(pre_sale % cur_sale)

[1 2 3 4 0]


In [509]:
# exponetial
print(pre_sale ** cur_sale)

[   1  256 2187 4096 3125]


In [513]:
# square root
# np.sqrt
print(np.sqrt(cur_sale))

[3.         2.82842712 2.64575131 2.44948974 2.23606798]


In [524]:
# matrix
arr = np.array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [522]:
x = []
for i in range(9):
    x.append(i)
x = np.array(x)
x.reshape(3,-1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])