### Numpy

A python library that works woth array created by Travis Oliphant and stands for Numerical Python

Numpy are faster than list due to the loclity of reference in computer science.

In [1]:
#### import numpy
import numpy as np

In [2]:
# creating an array of numbers
arr = np.array([9,7,5,3,1])
print(arr)

[9 7 5 3 1]


In [3]:
# an array object in numpy is called ndarray
# we pass a list,tuple,any array-object to array()
arr = np.array((2,4,6,8,0))
print(arr)

[2 4 6 8 0]


In [4]:
type(arr)

numpy.ndarray

#### dimensions in Arrays
- these are nested arrays

- 0-D Arrays

Zero dimension array or scalar

In [5]:
arr = np.array(34)
print(arr)

34


In [6]:
age = np.array(25)
print(age)

25


- 1-D Arrays

One dimension arrays or uni-dimensional

In [7]:
ages = np.array([25,23,27,29,30])
print(ages)

[25 23 27 29 30]


In [8]:
heights = np.array((123,122,100,123,98))
print(heights)

[123 122 100 123  98]


- 2-D arrays

Often used to represent __matrix__ or 2nd order tensors

In [9]:
health = np.array([[23,34,25,31],[123,200,192,128]])
print(health)

[[ 23  34  25  31]
 [123 200 192 128]]


- 3 D array

3rd order tensor, an array having 2-D arrays as its element

In [10]:
health_score = np.array([[[23,34,25,31],[123,200,192,128]],[[50,60,70,80],[99,88,77,66]]])
print(health_score)

[[[ 23  34  25  31]
  [123 200 192 128]]

 [[ 50  60  70  80]
  [ 99  88  77  66]]]


In [11]:
#### checking the dimensions
# ndim

In [12]:
print(health.ndim)

2


In [13]:
print(age.ndim)

0


In [14]:
print(health_score.ndim)

3


In [15]:
# There are no limit to number of dimensions
taste = np.array([11,22,33,44,55], ndmin=6)

In [16]:
print(taste)

[[[[[[11 22 33 44 55]]]]]]


In [17]:
print(taste.ndim)

6
