### Numpy

A python library that works woth array created by Travis Oliphant and stands for Numerical Python

Numpy are faster than list due to the loclity of reference in computer science.

In [1]:
#### import numpy
import numpy as np

In [2]:
# creating an array of numbers
arr = np.array([9,7,5,3,1])
print(arr)

[9 7 5 3 1]


In [3]:
# an array object in numpy is called ndarray
# we pass a list,tuple,any array-object to array()
arr = np.array((2,4,6,8,0))
print(arr)

[2 4 6 8 0]


In [4]:
type(arr)

numpy.ndarray

#### dimensions in Arrays
- these are nested arrays

- 0-D Arrays

Zero dimension array or scalar

In [5]:
arr = np.array(34)
print(arr)

34


In [6]:
age = np.array(25)
print(age)

25


- 1-D Arrays

One dimension arrays or uni-dimensional

In [7]:
ages = np.array([25,23,27,29,30])
print(ages)

[25 23 27 29 30]


In [8]:
heights = np.array((123,122,100,123,98))
print(heights)

[123 122 100 123  98]


- 2-D arrays

Often used to represent __matrix__ or 2nd order tensors

In [9]:
health = np.array([[23,34,25,31],[123,200,192,128]])
print(health)

[[ 23  34  25  31]
 [123 200 192 128]]


- 3 D array

3rd order tensor, an array having 2-D arrays as its element

In [10]:
health_score = np.array([[[23,34,25,31],[123,200,192,128]],[[50,60,70,80],[99,88,77,66]]])
print(health_score)

[[[ 23  34  25  31]
  [123 200 192 128]]

 [[ 50  60  70  80]
  [ 99  88  77  66]]]


In [11]:
#### checking the dimensions
# ndim

In [12]:
print(health.ndim)

2


In [13]:
print(age.ndim)

0


In [14]:
print(health_score.ndim)

3


In [15]:
# There are no limit to number of dimensions
taste = np.array([11,22,33,44,55], ndmin=6)

In [16]:
print(taste)

[[[[[[11 22 33 44 55]]]]]]


In [17]:
print(taste.ndim)

6


#### Accesing array by indexing

In [37]:
# accessing a 1-D array
meal_list = np.array(["Apples", "Bananas", "Oranges", "Grapes", "Berries", "Melons", "Carrots", "Potatoes", "Lettuce", "Tomatoes", "Cucumbers", "Broccoli", "Bread", "Pasta", "Rice", "Cereal", "Milk", "Cheese", "Yogurt", "Butter", "Beef", "Chicken", "Pork", "Fish", "Eggs", "Nuts", "Seeds", "Sweets", "Drinks"])
print(meal_list)

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']


In [38]:
print(meal_list.ndim)

1


In [31]:
# accesing the second item in meal_list
second_meal = meal_list[1]
print(second_meal)

Bananas


In [32]:
# accesing the last item in meal_list
last_meal = meal_list[-1]
print(last_meal)

Drinks


In [33]:
# accesing the 17th item in meal_list
seven_meal = meal_list[6]
print(seven_meal)

Carrots


In [35]:
# accessing a 2-D array

store_products = np.array(
    [
        ['product 1', 'product 2', 'product 3', 'product 4', 'product 5', 'product 6', 'product 7', 'product 8', 'product 9', 'product 10', 'product 11', 'product 12', 'product 13', 'product 14', 'product 15', 'product 16', 'product 17', 'product 18', 'product 19', 'product 20', 'product 21', 'product 22', 'product 23', 'product 24', 'product 25', 'product 26', 'product 27', 'product 28', 'product 29'],
        ["Apples", "Bananas", "Oranges", "Grapes", "Berries", "Melons", "Carrots", "Potatoes", "Lettuce", "Tomatoes", "Cucumbers", "Broccoli", "Bread", "Pasta", "Rice", "Cereal", "Milk", "Cheese", "Yogurt", "Butter", "Beef", "Chicken", "Pork", "Fish", "Eggs", "Nuts", "Seeds", "Sweets", "Drinks"]
    ]
)

print(store_products)

[['product 1' 'product 2' 'product 3' 'product 4' 'product 5' 'product 6'
  'product 7' 'product 8' 'product 9' 'product 10' 'product 11'
  'product 12' 'product 13' 'product 14' 'product 15' 'product 16'
  'product 17' 'product 18' 'product 19' 'product 20' 'product 21'
  'product 22' 'product 23' 'product 24' 'product 25' 'product 26'
  'product 27' 'product 28' 'product 29']
 ['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
  'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
  'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken'
  'Pork' 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']]


In [39]:
print(store_products.ndim)

2


In [41]:
# accesing the first item in store_product
print(store_products[0])

['product 1' 'product 2' 'product 3' 'product 4' 'product 5' 'product 6'
 'product 7' 'product 8' 'product 9' 'product 10' 'product 11'
 'product 12' 'product 13' 'product 14' 'product 15' 'product 16'
 'product 17' 'product 18' 'product 19' 'product 20' 'product 21'
 'product 22' 'product 23' 'product 24' 'product 25' 'product 26'
 'product 27' 'product 28' 'product 29']


In [43]:
# what about the first item in the first item
print(store_products[0][0])
# the pattern of accessing items is preferably used in List but not ideally in numpy array

product 1


In [44]:
# accessing the product 1 using numpy 
print(store_products[0,0])

product 1


In [67]:
# creating a 7-D array

seventh_dim = np.array(np.random.randint(10,100,10), ndmin=7)

In [68]:
print(seventh_dim)

[[[[[[[33 17 88 73 12 26 30 87 32 69]]]]]]]


In [69]:
# accesing the last item using list
last_item = seventh_dim[0][0][0][0][0][0][-1]
print(last_item)

69


In [70]:
# using numpy
last_item = seventh_dim[0,0,0,0,0,0,-1]
print(last_item)

69


#### Slicing

`arr[start:end:step,index]`

Slicing a 1-D array

In [71]:
print(meal_list)

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']


In [73]:
len(meal_list) # length of meal_list

29

In [75]:
# slice from begiinning to ending
meal_1 = meal_list[:]
print(meal_1)
# by default, start = 0, end = ending

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks'] 29


In [78]:
print(meal_list[0:])

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']


In [80]:
print(meal_list[:-1])
# last item was sliced out

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets']


In [85]:
print(meal_list[::2])
# be default step = 1, this returns the item after every two step

['Apples' 'Oranges' 'Berries' 'Carrots' 'Lettuce' 'Cucumbers' 'Bread'
 'Rice' 'Milk' 'Yogurt' 'Beef' 'Pork' 'Eggs' 'Seeds' 'Drinks']


Slicing a 2-D array

In [86]:
print(store_products)

[['product 1' 'product 2' 'product 3' 'product 4' 'product 5' 'product 6'
  'product 7' 'product 8' 'product 9' 'product 10' 'product 11'
  'product 12' 'product 13' 'product 14' 'product 15' 'product 16'
  'product 17' 'product 18' 'product 19' 'product 20' 'product 21'
  'product 22' 'product 23' 'product 24' 'product 25' 'product 26'
  'product 27' 'product 28' 'product 29']
 ['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
  'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
  'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken'
  'Pork' 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']]


In [91]:
# slicing the fisrt 5 item in the first list in the above 2-D array
print(store_products[0,:5])

['product 1' 'product 2' 'product 3' 'product 4' 'product 5']


In [90]:
# slicing the fisrt 5 item in the second list in the above 2-D array
print(store_products[1,:5])

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries']


In [93]:
# returning the second item in both list in the array
print(store_products[:,1])

['product 2' 'Bananas']


In [96]:
# returning the second item in both list in the array
print(store_products[0:,1])

['product 2' 'Bananas']


In [98]:
print(store_products[:,:])

[['product 1' 'product 2' 'product 3' 'product 4' 'product 5' 'product 6'
  'product 7' 'product 8' 'product 9' 'product 10' 'product 11'
  'product 12' 'product 13' 'product 14' 'product 15' 'product 16'
  'product 17' 'product 18' 'product 19' 'product 20' 'product 21'
  'product 22' 'product 23' 'product 24' 'product 25' 'product 26'
  'product 27' 'product 28' 'product 29']
 ['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
  'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
  'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken'
  'Pork' 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']]


#### data types

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

We can check the data type of an array `dtype`

In [100]:
print(meal_list)

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']


In [102]:
print(meal_list.dtype)

<U9


In [107]:
print(heights)

[123 122 100 123  98]


In [108]:
print(heights.dtype)

int64
