### Numpy

A python library that works woth array created by Travis Oliphant and stands for Numerical Python

Numpy are faster than list due to the loclity of reference in computer science.

All element in a numpy array are homogeneous while a list can have heteregeous elements


----
##### Array
An array is a grid of values and contains raw data.

In [1]:
#### import numpy
import numpy as np

In [2]:
# creating an array of numbers
arr = np.array([9,7,5,3,1])
print(arr)

[9 7 5 3 1]


In [3]:
# an array object in numpy is called ndarray
# we pass a list,tuple,any array-object to array()
arr = np.array((2,4,6,8,0))
print(arr)

[2 4 6 8 0]


In [4]:
type(arr)

numpy.ndarray

#### dimensions in Arrays
- these are nested arrays

- 0-D Arrays

Zero dimension array or scalar

In [5]:
arr = np.array(34)
print(arr)

34


In [6]:
age = np.array(25)
print(age)

25


- 1-D Arrays

One dimension arrays or uni-dimensional

In [7]:
ages = np.array([25,23,27,29,30])
print(ages)

[25 23 27 29 30]


In [8]:
heights = np.array((123,122,100,123,98))
print(heights)

[123 122 100 123  98]


- 2-D arrays

Often used to represent __matrix__ or 2nd order tensors

In [9]:
health = np.array([[23,34,25,31],[123,200,192,128]])
print(health)

[[ 23  34  25  31]
 [123 200 192 128]]


- 3 D array

3rd order tensor, an array having 2-D arrays as its element

In [10]:
health_score = np.array([[[23,34,25,31],[123,200,192,128]],[[50,60,70,80],[99,88,77,66]]])
print(health_score)

[[[ 23  34  25  31]
  [123 200 192 128]]

 [[ 50  60  70  80]
  [ 99  88  77  66]]]


In [11]:
#### checking the dimensions
# ndim

In [12]:
print(health.ndim)

2


In [13]:
print(age.ndim)

0


In [14]:
print(health_score.ndim)

3


In [15]:
# There are no limit to number of dimensions
taste = np.array([11,22,33,44,55], ndmin=6)

In [16]:
print(taste)

[[[[[[11 22 33 44 55]]]]]]


In [17]:
print(taste.ndim)

6


#### Accesing array by indexing

In [37]:
# accessing a 1-D array
meal_list = np.array(["Apples", "Bananas", "Oranges", "Grapes", "Berries", "Melons", "Carrots", "Potatoes", "Lettuce", "Tomatoes", "Cucumbers", "Broccoli", "Bread", "Pasta", "Rice", "Cereal", "Milk", "Cheese", "Yogurt", "Butter", "Beef", "Chicken", "Pork", "Fish", "Eggs", "Nuts", "Seeds", "Sweets", "Drinks"])
print(meal_list)

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']


In [38]:
print(meal_list.ndim)

1


In [31]:
# accesing the second item in meal_list
second_meal = meal_list[1]
print(second_meal)

Bananas


In [32]:
# accesing the last item in meal_list
last_meal = meal_list[-1]
print(last_meal)

Drinks


In [33]:
# accesing the 17th item in meal_list
seven_meal = meal_list[6]
print(seven_meal)

Carrots


In [35]:
# accessing a 2-D array

store_products = np.array(
    [
        ['product 1', 'product 2', 'product 3', 'product 4', 'product 5', 'product 6', 'product 7', 'product 8', 'product 9', 'product 10', 'product 11', 'product 12', 'product 13', 'product 14', 'product 15', 'product 16', 'product 17', 'product 18', 'product 19', 'product 20', 'product 21', 'product 22', 'product 23', 'product 24', 'product 25', 'product 26', 'product 27', 'product 28', 'product 29'],
        ["Apples", "Bananas", "Oranges", "Grapes", "Berries", "Melons", "Carrots", "Potatoes", "Lettuce", "Tomatoes", "Cucumbers", "Broccoli", "Bread", "Pasta", "Rice", "Cereal", "Milk", "Cheese", "Yogurt", "Butter", "Beef", "Chicken", "Pork", "Fish", "Eggs", "Nuts", "Seeds", "Sweets", "Drinks"]
    ]
)

print(store_products)

[['product 1' 'product 2' 'product 3' 'product 4' 'product 5' 'product 6'
  'product 7' 'product 8' 'product 9' 'product 10' 'product 11'
  'product 12' 'product 13' 'product 14' 'product 15' 'product 16'
  'product 17' 'product 18' 'product 19' 'product 20' 'product 21'
  'product 22' 'product 23' 'product 24' 'product 25' 'product 26'
  'product 27' 'product 28' 'product 29']
 ['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
  'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
  'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken'
  'Pork' 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']]


In [39]:
print(store_products.ndim)

2


In [41]:
# accesing the first item in store_product
print(store_products[0])

['product 1' 'product 2' 'product 3' 'product 4' 'product 5' 'product 6'
 'product 7' 'product 8' 'product 9' 'product 10' 'product 11'
 'product 12' 'product 13' 'product 14' 'product 15' 'product 16'
 'product 17' 'product 18' 'product 19' 'product 20' 'product 21'
 'product 22' 'product 23' 'product 24' 'product 25' 'product 26'
 'product 27' 'product 28' 'product 29']


In [43]:
# what about the first item in the first item
print(store_products[0][0])
# the pattern of accessing items is preferably used in List but not ideally in numpy array

product 1


In [44]:
# accessing the product 1 using numpy 
print(store_products[0,0])

product 1


In [67]:
# creating a 7-D array

seventh_dim = np.array(np.random.randint(10,100,10), ndmin=7)

In [68]:
print(seventh_dim)

[[[[[[[33 17 88 73 12 26 30 87 32 69]]]]]]]


In [69]:
# accesing the last item using list
last_item = seventh_dim[0][0][0][0][0][0][-1]
print(last_item)

69


In [70]:
# using numpy
last_item = seventh_dim[0,0,0,0,0,0,-1]
print(last_item)

69


#### Slicing

`arr[start:end:step,index]`

Slicing a 1-D array

In [71]:
print(meal_list)

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']


In [73]:
len(meal_list) # length of meal_list

29

In [75]:
# slice from begiinning to ending
meal_1 = meal_list[:]
print(meal_1)
# by default, start = 0, end = ending

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks'] 29


In [78]:
print(meal_list[0:])

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']


In [80]:
print(meal_list[:-1])
# last item was sliced out

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets']


In [85]:
print(meal_list[::2])
# be default step = 1, this returns the item after every two step

['Apples' 'Oranges' 'Berries' 'Carrots' 'Lettuce' 'Cucumbers' 'Bread'
 'Rice' 'Milk' 'Yogurt' 'Beef' 'Pork' 'Eggs' 'Seeds' 'Drinks']


Slicing a 2-D array

In [86]:
print(store_products)

[['product 1' 'product 2' 'product 3' 'product 4' 'product 5' 'product 6'
  'product 7' 'product 8' 'product 9' 'product 10' 'product 11'
  'product 12' 'product 13' 'product 14' 'product 15' 'product 16'
  'product 17' 'product 18' 'product 19' 'product 20' 'product 21'
  'product 22' 'product 23' 'product 24' 'product 25' 'product 26'
  'product 27' 'product 28' 'product 29']
 ['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
  'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
  'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken'
  'Pork' 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']]


In [91]:
# slicing the fisrt 5 item in the first list in the above 2-D array
print(store_products[0,:5])

['product 1' 'product 2' 'product 3' 'product 4' 'product 5']


In [90]:
# slicing the fisrt 5 item in the second list in the above 2-D array
print(store_products[1,:5])

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries']


In [93]:
# returning the second item in both list in the array
print(store_products[:,1])

['product 2' 'Bananas']


In [96]:
# returning the second item in both list in the array
print(store_products[0:,1])

['product 2' 'Bananas']


In [98]:
print(store_products[:,:])

[['product 1' 'product 2' 'product 3' 'product 4' 'product 5' 'product 6'
  'product 7' 'product 8' 'product 9' 'product 10' 'product 11'
  'product 12' 'product 13' 'product 14' 'product 15' 'product 16'
  'product 17' 'product 18' 'product 19' 'product 20' 'product 21'
  'product 22' 'product 23' 'product 24' 'product 25' 'product 26'
  'product 27' 'product 28' 'product 29']
 ['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
  'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
  'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken'
  'Pork' 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']]


#### data types


 __Data Type	and their Description__
- i	Signed integer
- b	Boolean (True or False)
- u	Unsigned integer
- f	Floating-point number
- c	Complex number (real and imaginary parts)
- m	Timedelta (representing a duration)
- M	Datetime (specific point in time)
- O	Object (can store any Python object)
- S	String (fixed-length sequence of characters)
- U	Unicode string (fixed-length sequence of Unicode characters)
- V	Void (fixed-size raw memory buffer)

In [100]:
print(meal_list)

['Apples' 'Bananas' 'Oranges' 'Grapes' 'Berries' 'Melons' 'Carrots'
 'Potatoes' 'Lettuce' 'Tomatoes' 'Cucumbers' 'Broccoli' 'Bread' 'Pasta'
 'Rice' 'Cereal' 'Milk' 'Cheese' 'Yogurt' 'Butter' 'Beef' 'Chicken' 'Pork'
 'Fish' 'Eggs' 'Nuts' 'Seeds' 'Sweets' 'Drinks']


In [102]:
print(meal_list.dtype)

<U9


In [107]:
print(heights)

[123 122 100 123  98]


In [109]:
print(heights.dtype)

int64


In [139]:
date = np.array(['2002-01-01', '2003-02-21'])

In [140]:
print(date.dtype)

<U10


#### creating defined data type

`dtype='V'`

In [143]:
# defining the array as a Datetime data type

date = np.array(['2002-01-01', '2003-02-21'], dtype='M')

In [144]:
print(date.dtype)

datetime64[D]


#### we can define the size(byte) of some data type

`i,u,f,S,U`

`dtype='S10'`

In [147]:
fruit = np.array(['Carrots', 'Potatoes', 'Lettuce', 'Tomatoes'], dtype='S10')

In [148]:
print(fruit)

[b'Carrots' b'Potatoes' b'Lettuce' b'Tomatoes']


In [163]:
dice = np.array([1,2,3,4,5,6,7,8,9,0], dtype='i2')

In [164]:
print(dice)

[1 2 3 4 5 6 7 8 9 0]


In [165]:
print(dice.dtype)

int16


In [176]:
charr = np.array(['a', 2, 3], dtype='i')
# this returns an error when we try converting the datatype to 'i' (integer) due to the presence of 'STRING'

ValueError: invalid literal for int() with base 10: 'a'

In [177]:
# we can convert integer to string but not the other way
charr = np.array(['a', 2, 3], dtype='S')
print(charr.dtype)

|S1


#### astype()

- best way to change the data type of an existing array

- Always ake a copy 

```
arr = np.array([1,2,3,4,5])
newarr = arr.astype('f')
```

In [191]:
score = np.array([60,45,98,100,-56, 0])
print(score)
print(score.dtype)

[ 60  45  98 100 -56   0]
int64


In [192]:
# changing the data type to float
new_score = score.astype('f')
print(new_score)
print(new_score.dtype)

[ 60.  45.  98. 100. -56.   0.]
float32


In [193]:
# try converting data type to boolean
bool_score = score.astype(bool)
print(bool_score)
print(bool_score.dtype)
# all numbers are TRUE but 0

[ True  True  True  True  True False]
bool


#### copy vs view

Copy creates a new array and any data manipulation doesn't affect the original array

View returns the original array and any manipulation affects the original array

In [214]:
# copy
phone_brands = [
    "Samsung",
    "Apple",
    "Huawei",
    "Sony",
    "Nokia",
    "Google",
    "OnePlus",
    "HTC",
    "ASUS"
]
phone_brands = np.array(phone_brands)

In [215]:
new_phones = phone_brands.copy()
print(new_phones)

['Samsung' 'Apple' 'Huawei' 'Sony' 'Nokia' 'Google' 'OnePlus' 'HTC' 'ASUS']


In [216]:
# lets replace 'HTC' to 'Vivo'
new_phones[7] = 'Vivo'
print(phone_brands)
print(new_phones)
# the orignal array is not affected

['Samsung' 'Apple' 'Huawei' 'Sony' 'Nokia' 'Google' 'OnePlus' 'HTC' 'ASUS']
['Samsung' 'Apple' 'Huawei' 'Sony' 'Nokia' 'Google' 'OnePlus' 'Vivo'
 'ASUS']


In [223]:
# view
colors = [
    "red",  
    "orange", 
    "yellow", 
    "green", 
    "blue", 
    "indigo",  
    "purple", 
    "pink"
]
colors = np.array(colors)

In [224]:
new_colors = colors.view()
print(new_colors)

['red' 'orange' 'yellow' 'green' 'blue' 'indigo' 'purple' 'pink']


In [226]:
# lets replace 'pink' to maroon
new_colors[-1] = 'maroon'
print(colors)
print(new_colors)
# both the new array and the original array has been affected

['red' 'orange' 'yellow' 'green' 'blue' 'indigo' 'purple' 'maroon']
['red' 'orange' 'yellow' 'green' 'blue' 'indigo' 'purple' 'maroon']


__How do we know if an array owns its data?__

copies owns their data, as any data manipulation to it does not affect the orignal data

view does not own its data and any manipulation affects the orignal array

calling the `base` attribute on an array returns __None__ if the array owns its data, else it returns the array

In [230]:
print(new_colors.base) # copy
print(new_phones.base) # view

['red' 'orange' 'yellow' 'green' 'blue' 'indigo' 'purple' 'maroon']
None


#### Shape
This returns a tuple showing the size of the array along size its dimension


In [298]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print('shape',arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
shape (2, 4)


In [297]:
arr = np.array([[1,2,3],[5,6,7],[6,7,8],[9,1,2]])
print(arr)
print('shape', arr.shape)

[[1 2 3]
 [5 6 7]
 [6 7 8]
 [9 1 2]]
shape (4, 3)


In [300]:
arr = np.array(np.random.normal(10,20,5), ndmin=1)
print(arr)
print('shape', arr.shape)

[-3.48455058 29.75033767 56.30315122 15.27172273 24.6762351 ]
shape (5,)


In [303]:
arr = np.array(np.random.normal(10,20,5), ndmin=3)
print(arr)
print('shape', arr.shape)

[[[33.97490283 19.8717124  -0.12290764 -3.49690681 -6.31337058]]]
shape (1, 1, 5)


In [309]:
arr = np.array([np.random.normal(10,20,2) for i in range(5)], ndmin=2)
print(arr)
print('shape', arr.shape)

[[38.95324785  7.12600445]
 [48.57049425 29.78563091]
 [36.35906005 19.15735896]
 [-6.26322141  9.37084197]
 [11.17694376 48.99984103]]
shape (5, 2)


In [325]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


#### Reshape

This is the changing of the shape of an array

`reshape(row,columns,subarrays)`

In [352]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [353]:
print(arr)
print(arr.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [354]:
# reshape
newarr = arr.reshape(5,2)

In [355]:
print(newarr)
print('array shape', newarr.shape)
print('array dimension', newarr.ndim)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [356]:
# note that you can only reshape it to fit
newarr = arr.reshape(3,2)
# this returns an error

ValueError: cannot reshape array of size 10 into shape (3,2)

In [357]:
newarr = arr.reshape(2,5) # 2-D array

In [358]:
print(newarr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [360]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [361]:
newarr = arr.reshape(2, 3, 2) # 3-D array
# [ [  [][][]  ]    [  [][][]   ]   ]

In [362]:
print(newarr)
print('array shape', newarr.shape)
print('array dimension', newarr.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [378]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [379]:
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [380]:
arr.reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [383]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [384]:
arr.reshape(4,6,2)

ValueError: cannot reshape array of size 32 into shape (4,6,2)

In [387]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191])

In [389]:
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191]


In [391]:
newarr = arr.reshape(8,2,3,4)

In [392]:
print('array shape', newarr.shape)
print('array dimension', newarr.ndim)

array shape (8, 2, 3, 4)
array dimension 4


In [385]:
8*2*3*4

192

In [386]:
x = []
for i in range(192):
    x.append(i)
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191]
